config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/home', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/two_factor_auth', to: 'two_factor_auth#new'
  post '/two_factor_auth_verify', to: 'two_factor_auth#create'
  get '/two_factor_login_verify', to: 'two_factor_auth#verify'
  post '/two_factor_login_verify', to: 'two_factor_auth#verify_post'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    # [BUG] sbx@kumar--.ninja is acceptable. Domain name should not be ended with hyphens
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token for remember me.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    include SessionsHelper
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.encrypted_2fa_secret.nil?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user
      else
        # Creating state for two factor verify, so that attacker can't manipulate the user id
        # Login and check url for tfa enbale users to understand the above statement.
        user.update_attribute(:two_factor_state, SecureRandom.alphanumeric(30))
        redirect_to controller: 'two_factor_auth', action: 'verify', id: user.id, state: user.two_factor_state
      end
    else
      flash.now[:danger] = "Invalid email or password combination" # Not quite right :/
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
  
end

app/controllers/two_factor_auth_controller.rb
class TwoFactorAuthController < ApplicationController

  def new
    if params[:twoFA][:twoFA_auth] == "on"
      # Enable 2FA
      @secret_2fa = ROTP::Base32.random_base32
      $global_secret_2fa = @secret_2fa
      totp = ROTP::TOTP.new(@secret_2fa)
      @user = User.find_by(id: params[:twoFA][:twoFA_userId])
      qr_link = totp.provisioning_uri(@user.email + "(Blackbox)")
      totp = nil
      @qr = RQRCode::QRCode.new(qr_link)
      @qr = @qr.as_png(size: 400)
    elsif params[:twoFA][:twoFA_auth] == "off"
      @user = User.find_by(id: params[:twoFA][:twoFA_userId])
      @user.update_attribute(:encrypted_2fa_secret, nil)
      redirect_to user_url(@user)
    end
  end

  def create
    totp = ROTP::TOTP.new($global_secret_2fa)
    if totp.now() == params[:twoFA][:otp]
      # Linked successfully, save the encrypted otp in database
      key = ActiveSupport::KeyGenerator.new('blackbox').generate_key(Rails.application.credentials.dig(:salt_2fa), 32)
      crypt = ActiveSupport::MessageEncryptor.new(key)
      encrypted_data = crypt.encrypt_and_sign($global_secret_2fa)
      $global_secret_2fa = nil
      @user = User.find_by(id: params[:twoFA][:twoFA_userId])
      @user.update_attribute(:encrypted_2fa_secret, encrypted_data)
    else
      render :status => 403 
    end
  end

  def verify
    @user = User.find_by(id: params[:id])
    if @user.two_factor_state != params[:state]
      redirect_to login_url
    end
  end

  # Definition for verify action POST request
  def verify_post
    user = User.find_by(id: params[:otp][:twoFA_userId])
    key = ActiveSupport::KeyGenerator.new('blackbox').generate_key(Rails.application.credentials.dig(:salt_2fa), 32)
    crypt = ActiveSupport::MessageEncryptor.new(key)
    secret = crypt.decrypt_and_verify(user.encrypted_2fa_secret)
    totp = ROTP::TOTP.new(secret)
    secret = nil
    crypt = nil
    key = nil
    if params[:otp][:otp] == totp.now()
      # Destroying 2fa state
      user.update_attribute(:two_factor_state, nil)
      log_in user
      flash[:success] = "Login was successful, Welcome! ~Mr. Robot"
      redirect_to user_url(user)
    else
      redirect_to controller: 'two_factor_auth', action: 'verify', id: user.id, state: user.two_factor_state
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Sign up was successful, Welcome! ~Mr. Robot"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Blackbox"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    # Forgets a persistent session.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/two_factor_auth_helper.rb
module TwoFactorAuthHelper
end

app/helpers/users_helper.rb
module UsersHelper

    # Returns for Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        return image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
        <ul>
            <li> <%= link_to "About", about_path %></li>
            <li> <%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Blackbox", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Home", root_path %> </li>
            <% if logged_in? %>
              <!-- <li><%= link_to "Users", '#' %></li> -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form conatins <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1> Welcome to Blackbox </h1>

    <h2>
        All file sharing sevice at one place.
    </h2>

    <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/two_factor_auth/new.html.erb
<% provide(:title, "Set up two factor authentication") %>

<div>
    <h2 style="text-align: left !important; font-size: 1.9 !important"><%= @user.name %>'s Account Settings</h2>
    <hr class="style1">
</div>

<div>
    <h3>Two factor authentication setup</h3>
    <div>
        <p>Open Google Authenticator. Select "Add account" or "+" and scan the QR code below:</p>
        <%= image_tag(@qr.to_data_url, size: "400x400", class: "img-thumbnail img-responsive center-block") %>
        <br>        
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#step-one" aria-controls="step-one" role="tab" data-toggle="tab">Step 1</a></li>
            <li role="presentation"><a href="#next" aria-controls="next" role="tab" data-toggle="tab">Next</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="step-one">
                <div>
                    <p style="display: inline-block">Enter your secret key manually if you're unable to scan the QR code: </p>
                    <pre style="overflow: inherit; display: inline-block"><%= @secret_2fa %></pre>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="next">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <p>Enter the security code generated by your mobile authenticator app to make sure it’s configured correctly.</p>
                        <%= form_with scope: :twoFA, url: two_factor_auth_verify_path do |f| %>
                            <%= f.hidden_field :twoFA_userId, value: @user.id, class: "form-control" %>  
                            <%= f.text_field :otp, class: "form-control" %>
                            <%= f.submit "Submit" %>
                        <% end %>
                    </div>
                </div>
            </div>

            <div role="tabpanel" class="tab-pane" id="success">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <p>Two factor authentication enabled successfully!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/two_factor_auth/verify.html.erb
<% provide(:title, "Two factor authentication check") %>

<h2 style="text-align: left !important; font-size: 1.9em !important">Two factor authentication check</h2>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:otp, url: two_factor_login_verify_path) do |f| %>

            <%= f.label :otp, "Enter OTP" %>
            <%= f.text_field :otp, class: 'form-control' %>
            <%= f.hidden_field :twoFA_userId, value: @user.id %>  
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "#{@user.name}'s Settings") %>

<div>
    <h2 style="text-align: left !important; font-size: 1.9em !important"><%= @user.name %>'s Account Settings</h2>
</div>

<div>

    <div>
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">General</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Security</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Connected Services</a>
        </li>
        </ul>
    </div>

    <div>
        <div class="tab-content" id="pills-tabContent">

        <!-- Connected Services section goes here -->
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">THIS IS GENERAL STUFF</div>
    
        <!-- Security section goes here -->
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <div>
                <div id="security">
                    <h4>Two factor authentication</h4>
                    <h5 class="text-muted">Requires Google Authenticator</h5>
                </div>
                <div id="security" class="pull-right">
                    <%= form_for(:twoFA, url: two_factor_auth_path) do |f| %>
                        <% if @user.encrypted_2fa_secret.nil? %>
                        
                            <%= f.hidden_field :twoFA_auth, value: "on" %>  
                            <%= f.hidden_field :twoFA_userId, value: @user.id %>                          
                            <%= f.submit "Turn on", class: "btn btn-success twoFA_twoFA_auth" %>
                        <% else %>
                            <%= f.hidden_field :twoFA_auth, value: "off" %>  
                            <%= f.hidden_field :twoFA_userId, value: @user.id %>                          
                            <%= f.submit "Turn off", class: "btn btn-danger twoFA_twoFA_auth" %>
                        <% end %>
                    <% end %>
                </div>
                <hr class="style1">
            </div>
        </div>

        <!-- Connected Services section goes here -->
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">THIS IS FOR CONNECTED SERVICES STUFF</div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>

<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: signup_path) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>